language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t robinraphel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true robinraphel/docker-react npm run test